# Generated by Django 4.2.5 on 2023-09-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="Employee of the month",
        ),
        migrations.AddField(
            model_name="employee",
            name="is_eotm",
            field=models.BooleanField(
                default=False, verbose_name="Employee of the month"
            ),
        ),
    ]
