# Generated by Django 4.2.5 on 2023-10-02 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_remove_employee_employee_of_the_month_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="eotm_wins",
            field=models.PositiveIntegerField(default=0, verbose_name="EOTM Wins"),
        ),
        migrations.CreateModel(
            name="EOTMDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_detail", models.TextField(max_length=600)),
                ("number_of_likes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "commentor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
