# Generated by Django 4.2.5 on 2023-10-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_alter_employee_eotm_wins_eotmdetail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eotmdetail",
            old_name="commentor_id",
            new_name="commentor",
        ),
        migrations.AlterField(
            model_name="eotmdetail",
            name="comment_detail",
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="eotmdetail",
            name="number_of_likes",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
