# Generated by Django 4.2.5 on 2023-10-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_remove_eotmdetail_number_of_likes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="description",
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
